services:
  - type: web
    name: laravel-api
    env: docker
    plan: free
    region: oregon
    buildCommand: ""
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
    autoDeploy: true
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
